config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),

]+i18n_patterns(
    path('i18n',include('django.conf.urls.i18n')),
    path('news/', include('newsapp.urls')),
    path('account/', include('accounts.urls'))
)

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newsapp/urls.py
from  django.urls import path
from .views import (ListPageView, DetailPageVieaw,
                    HomePageView, ContactPageView,
                    LocalNewsView, XorijNewsView,
                    SportNewsView, TechnologyNewsView,
                    UpdateNewsView, DeleteNewsView,
                    CreateNewsView, SearchListView, EditCommentView, DeleteCommentView, NewsLikeView)


app_name = 'newsapp'


urlpatterns = [
    path('search/',SearchListView.as_view(),name='search'),
    path('', HomePageView.as_view(),name='home_page'),
    path('create/',CreateNewsView.as_view(),name='create_news'),
    path('contact-us/',ContactPageView.as_view(),name='contact_page'),
    path('all-news/',ListPageView.as_view(),name='list_page'),
    path('local/',LocalNewsView.as_view(),name='local_news'),
    path('xorij/',XorijNewsView.as_view(),name='xorij_news'),
    path('sport/',SportNewsView.as_view(),name='sport_news'),
    path('technology/',TechnologyNewsView.as_view(),name='tech_news'),
    path('<slug:slug>/update/', UpdateNewsView.as_view(), name='update_news'),
    path('<slug:slug>/delete/', DeleteNewsView.as_view(), name='delete_news'),
    path('<slug:slug>/', DetailPageVieaw.as_view(), name='detail_page'),

    path('comment/<int:pk>/edit/',EditCommentView.as_view(),name='edit_comment'),
    path('comment/<int:pk>/delete/',DeleteCommentView.as_view(),name='delete_comment'),


    path("like/<slug:slug>/",NewsLikeView.as_view(),name='like'),
]

newsapp/models.py
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import models

from django.utils import timezone

from newsapp.managers import PublishedManager
from django.utils.text import slugify
class Category(models.Model):
    name =models.CharField(max_length=255)

    def __str__(self):
        return self.name


class News(models.Model):
    class Status(models.TextChoices):
        Draft = 'DF','Draft'
        Published = "PB","Published"
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    body = models.TextField()
    image = models.ImageField(upload_to='news/images')
    # author = models.ForeignKey(User,blank=True,null=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    published_time = models.DateTimeField(default=timezone.now)
    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,default=Status.Draft,choices=Status.choices)

    objects = models.Manager() #default manager
    published = PublishedManager()

    #save funkisyasini over rayt qilamiz
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)
        
    class Meta:
        ordering = ['-published_time']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('newsapp:detail_page', args=[self.slug])


class UserCountNews(models.Model):
    pass



class ContactModel(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    text = models.TextField()


    def __str__(self):
        return f"{self.name} {self.email}"

class Comment(models.Model):
    news = models.ForeignKey(News,on_delete=models.CASCADE,related_name='comments')
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='comments')
    body = models.TextField()
    active = models.BooleanField(default=True)
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_time']

    def __str__(self):
        return f"Comment - {self.body} by {self.user}"


class NewsLike(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='likes')
    news = models.ForeignKey(News,on_delete=models.CASCADE,related_name='likes')
    class Meta:
        constraints =[
            models.UniqueConstraint(fields=['user','news'],name='unique_like')
        ]

newsapp/forms.py
from django.forms import Form,ModelForm
from .models import ContactModel, Comment
from django import forms
class ContactForm(ModelForm):
    class Meta:
        model = ContactModel
        # fields = ['name','email','phone','massage']
        fields = '__all__'

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

newsapp/views.py
from lib2to3.fixes.fix_input import context
from django.db.models import Q, Count
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.db.models import Q
from django.db.transaction import commit
from django.shortcuts import render, get_object_or_404, redirect
from django.template.defaulttags import comment
from django.urls import reverse_lazy
from hitcount.models import HitCount
from hitcount.utils import get_hitcount_model
from hitcount.views import HitCountDetailView
from django.core.paginator import Paginator
from django.views import View
from django.views.generic import TemplateView, ListView, UpdateView, DeleteView, CreateView
from unicodedata import category

from config.custom_mixins import CheckUserLogin_and_Admin
from newsapp.forms import ContactForm, CommentForm
from newsapp.models import News, Category, Comment, NewsLike
from django.http import HttpResponse
from django.utils.translation import get_language
"""class view"""
class ListPageView(View):
    def get(self,request):
        news_list = News.published.all()
        context = {
            'news_list':news_list
        }
        return render(request,'news_list.html',context)
"""funkisya view"""
# def ListPageView(request):
#     news_list = News.published.all()#unversial usulda filtrlash
#     # news_list = News.objects.filter(status=News.Status.Published)
#     cantext = {
#         'news_list':news_list
#     }
#     return render(request,'news_list.html',cantext)
"""class detail view """
class DetailPageVieaw(HitCountDetailView,LoginRequiredMixin,View):
    def get(self, request, slug):
        comment_form = CommentForm()
        news_detail = get_object_or_404(News, slug=slug, status=News.Status.Published)
        # print('news_detail', news_detail)
        comments = news_detail.comments.filter(active=True)
        likes_count = news_detail.likes.count()
        is_liked = news_detail.likes.filter(user=request.user).exists()
        hit_count = HitCount.objects.get_for_object(news_detail)
        hit_count_response = self.hit_count(request,hit_count)
        hit_count.refresh_from_db()
        coment_count =  comments.count()


        context = {
            'news_detail': news_detail,
            'comments':comments,
            'comment_form':comment_form,
            'hit_count_response':hit_count_response,
            'hit_count':hit_count,
            'coment_count':coment_count,
            'likes_count':likes_count,
            'is_liked':is_liked
        }
        return render(request, 'news_detail.html', context)
    def post(self,request,slug):
        news_detail = get_object_or_404(News, slug=slug, status=News.Status.Published)
        comments = news_detail.comments.filter(active=True)
        new_comment = None
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.news = news_detail
            new_comment.user = request.user
            new_comment.save()
            return redirect('newsapp:detail_page',slug=news_detail.slug)
        context = {
            'news_detail': news_detail,
            'comments':comments,
            'new_comment':new_comment,
            'comment_form':comment_form,
        }
        return render(request, 'news_detail.html', context)

class TopNewsView(View):
    def get(self, request):
        news_type = ContentType.objects.get_for_model(News)
        hit_counts = HitCount.objects.filter(
            content_type=news_type
        ).order_by('-hits')[:6]
        news_hit = []
        for hit in hit_counts:
            try:
                news = News.objects.get(pk=hit.object_pk, status=News.Status.Published)
                news_hit.append(news)
            except News.DoesNotExist:
                continue

        context = {
            'news_hit': news_hit
        }
        return render(request, 'home.html', context)

class NewsLikeView(View):
    def post(self,request,slug):
        news = get_object_or_404(News,slug=slug)
        try:
            is_liked = news.likes.get(news=news,user=request.user)
            is_liked.delete()

        except NewsLike.DoesNotExist:
            NewsLike.objects.create(news=news,user=request.user)

        return redirect('newsapp:detail_page',slug=news.slug)


def get_category_db(name_uz):
    category = Category.objects.filter(name_uz=name_uz).first()

    if not category:
        return News.objects.none()
    return News.objects.filter(category=category).order_by('-published_time')[:6]


"""funkisya detiel view"""
# def DetailPageVieaw(request,id):
#     news_detail = News.published.get(id=id)
#     context = {
#         'news_detail':news_detail
#     }
#
#     return render(request,'news_detail.html',context)

"""homepage view"""

class HomePageView(View):
    def get(self,request):
        categories = Category.objects.all()
        current_language = get_language()
        # print('current_language',current_language)
        news_list = News.published.all().order_by('-published_time')
        latest_news_list = News.published.all().order_by('-published_time')[:5]
        # most_likes_count = News.objects.all().order_by('-likes')[:5]
        most_likes_count = News.published.annotate(
            like_count=Count('likes')
        ).order_by('-like_count').distinct()[:5]
        print('most_likes_count', most_likes_count)


        # local_news = News.published.filter(category__name="maxalliy").order_by('-published_time')[:6]
        # xorij_news = News.published.filter(category__name="xorij").order_by('-published_time')[:6]
        # texnology_news = News.published.filter(category__name="texnalogiya").order_by('-published_time')[:6]
        # sport_news = News.published.filter(category__name="sport").order_by('-published_time')[:6]#agar nargi usulda bo'lsa [1:6]
        local_news = get_category_db('maxalliy')
        texnology_news = get_category_db('texnalogiya')
        xorij_news = get_category_db('xorij')
        sport_news = get_category_db('sport')

        context = {
            'xorij_news':xorij_news,
            'news_list': news_list,
            'local_news': local_news,
            'latest_news_list': latest_news_list,
            'texnology_news':texnology_news,
            'sport_news':sport_news,
            'categories':categories,
            'most_likes_count':most_likes_count,
        }
        return render(request,'home.html',context)

    """contact view """
# class ContactPageView(View):
#     def get(self,request):
#         return render(request,'contact.html')
class ContactPageView(TemplateView):
    def get(self,request, *args, **kwargs):
        forms_page = ContactForm()
        context = {
            'forms_page':forms_page,
        }
        return render(request,'contact.html',context)
        # return self.render_to_response(request)
    def post(self,request,*args, **kwargs):
        forms_page = ContactForm(request.POST)
        if forms_page.is_valid():
            forms_page.save()
            return HttpResponse("<h1> sizning habaringiz yetib keldi </h1>")
        else:
            context = {
                'forms_page': forms_page,
            }
            return render(request, 'contact.html', context)
""" bu funkisya categoryani turli tilda ishlashi uchun"""
def get_category_db_(name_uz_val):
    category =  Category.objects.filter(name_uz=name_uz_val).first()
    if not category:
        return News.objects.none()
    return News.objects.filter(category=category).order_by('id')

class LocalNewsView(ListView):
    model = News
    template_name = 'local_news.html'
    context_object_name = 'page_obj'


    def get_queryset(self):
        # news = self.model.published.all().filter(category__name="maxalliy")
        news = get_category_db_('maxalliy')
        page_size=self.request.GET.get('page_size',2)
        pagination = Paginator(news,page_size)
        page_number = self.request.GET.get('page')
        page_obj = pagination.get_page(page_number)
        # print('page_obj',page_obj)

        return page_obj





class XorijNewsView(ListView):
    model = News
    template_name = 'xorij_news.html'
    context_object_name = 'xorijnews_list'

    def get_queryset(self):
        # news = self.model.published.all().filter(category__name="xorij")
        news = get_category_db_('xorij')
        return news


class SportNewsView(ListView):
    model = News
    template_name = 'sport_news.html'
    context_object_name = 'sportnews_list'

    def get_queryset(self):
        # news = self.model.published.all().filter(category__name="sport")
        news = get_category_db_('sport')
        return news


class TechnologyNewsView(ListView):
    model = News
    template_name = 'texnalogya_news.html'
    context_object_name = 'texnalogyanews_list'

    def get_queryset(self):
        # news = self.model.published.all().filter(category__name="texnalogiya")
        news = get_category_db_('texnalogiya')
        return news


class UpdateNewsView(CheckUserLogin_and_Admin,UpdateView):
    model = News
    template_name = 'crud/update_news.html'
    fields = [ 'title','body','image','category','status',]

class DeleteNewsView(CheckUserLogin_and_Admin,DeleteView):
    model = News
    template_name = 'crud/delete_news.html'
    success_url = reverse_lazy('newsapp:home_page')

class CreateNewsView(CheckUserLogin_and_Admin,CreateView):
    model = News
    template_name =  'crud/create_news.html'
    fields = ['title','title_uz','title_en','title_ru',
              'body','body_uz','body_en','body_ru',
              'image',
              'category','status']


# class CommentView(View):
#     def get(self,request):
#         return render(request,'comment.html')
#     def post(self,request):
#         pass

class SearchListView(ListView):
    model = News
    template_name = 'searching_list.html'

newsapp/templates/delete_confirm_comment.html
{% extends 'base.html' %}
{% load static %}
{% load hitcount_tags %}

{% block title %}izohni o'chirishni tasdiqlash sahifasi saxifasi{% endblock title %}
{% block content %}
<h2>izohni o'chirishni tasdiqlang</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Izohni o'chirish</button>
</form>
<button><a href="{% url 'newsapp:detail_page' slug=delete_comment.news.slug %}">orqaga
</a></button>
{% endblock content %}

newsapp/templates/edit_comment.html
{% extends 'base.html' %}
{% load static %}
{% load hitcount_tags %}

{% block title %}izohni tahrirlash saxifasi{% endblock title %}
{% block content %}
<h1>Izohni tahrirlash </h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Izohni saqlash</button>
</form>
<!--<button action="{% url 'newsapp:detail_page' slug=comment.news.slug %}" class="btn btn-warning">Ortaga qaytish</button>-->
<a href="{% url 'newsapp:detail_page' slug=comment.news.slug %}" class="btn btn-primary">ortga qaytish</a>
{% endblock content %}

newsapp/templates/local_news.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Xorij habarlar {% endblock title %}
{% block content %}
{% for local in page_obj %}
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <a href="{{ local.get_absolut_url }}">
                <img src="{{ local.image.url }}" alt="{{local.title }}" style="width: 100%; margin-bottom: 15px;">
            </a>
        </div>
        <div class="col-sm-8">
            <a href="{{ local.get_absolute_url }}">
                <h2><b>{{ local.title }}</b></h2>
            </a>
            <p>{{ local.body| truncatewords:50}}</p>
           <p>{{ local.published_time }}</p>
        </div>
    </div>
</div>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock content %}

newsapp/templates/news_detail.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load hitcount_tags %}

{% block title %}Detail{% endblock title %}
{% block content %}
<div class="container">
    <div class="row align-items-center">
        <div class="col-lg-6">
            <img class="cover-pic" src="{{ news_detail.image.url }}" alt="{{ news_detail.title }}" style="width:100%">
        </div>
        <div class="col-lg-6">
            <h1>{{ news_detail.title }}</h1>
            <hr>
            <h4 class="text-muted">Kategoriya: <span class="text-primary">{{ news_detail.category }}</span></h4>


            {% if request.user.is_authenticated %}
            <form action="{% url 'newsapp:like' news_detail.slug  %}" method="post" style=" display:inline-blok;">
                {% csrf_token %}
                {% if is_liked %}
                    <p><i class="fa-solid fa-clock"></i>{{ news_detail.published_time }}
                    |{% blocktranslate %}  <i class="fa-solid fa-eye">{% endblocktranslate %}{% get_hit_count for news_detail %} |</i>
                    <button type="submit"  class="fa-solid fa-heart" style="border:none; background:none; color:red ;"></button>{{likes_count}} </p>
                {% else %}
                    <p><i class="fa-solid fa-clock"></i>{{ news_detail.published_time }}
                    |{% blocktranslate %}  <i class="fa-solid fa-eye">{% endblocktranslate %}{% get_hit_count for news_detail %} |</i>
                    <button type="submit"  class="fa-regular fa-heart" style="border:none; background:none; color:grey; "></button> {{likes_count}} </p>
                {% endif %}
            </form>
            {% endif %}
            <p class="lead">{{ news_detail.body }}</p>
        </div>
        <div class="text-center">
            {% if request.user.is_superuser and request.user.is_authenticated %}
                <a href="{% url 'newsapp:update_news' news_detail.slug %}" class="btn btn-info"> Taxrirlash </a>
                <a href="{% url 'newsapp:delete_news' news_detail.slug %}" class="btn btn-danger"> O'chirish </a>

            {% endif %}
        </div>
    </div>
    {% if comments %}
        <h1 class="text-danger">{% blocktranslate %} Izohlar {% endblocktranslate %}</h1>
        <h3>Izohlar soni {{ coment_count }} ta </h3>
        {% for comment in comments %}
            <i class="fa-solid fa-user-secret"><h3>{{ comment.user.username }}</h3></i>
            {% if request.user == comment.user %}
            <a href="{% url 'newsapp:edit_comment' pk=comment.pk %}"><i class="fa-solid fa-pencil">Tahrirlash</i></a>
            <a href="{% url 'newsapp:delete_comment' pk=comment.pk %}"><i class="fa-solid fa-trash">o'chirish</i></a>
            {% endif %}
            <i class="fa-solid fa-calendar-days"><span>{{ comment.created_time }}</span></i>
            <p>{{ comment.body }}</p>
        {% endfor %}
    {% endif %}
    <h1>{% blocktranslate %}Izoh qoldirish{% endblocktranslate %} </h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <button type="submit" class="btn btn-primary">Izoh saqlash</button>
        </form>
    </div>
</div>
{% endblock content %}

newsapp/templates/news_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>News List Page</title>
</head>
<body>
      <h1>
        News List Page
      </h1>
      {%for news in news_list %}
      <img style="width : 500px" src="{{news.image.url}}" alt="{{news.title}}">
      <a href="{% url 'newsapp:detail_page' news.id %}"><h2>{{news.title}}</h2></a>
      <h2>{{news.title}}</h2>
      <p>{{news.status}}</p>
      {%endfor %}
</body>
</html>

newsapp/templates/sport_news.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Xorij habarlar {% endblock title %}
{% block content %}
{% for sport in sportnews_list %}
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <a href="{{ sport.get_absolut_url }}">
                <img src="{{ sport.image.url }}" alt="{{sport.title }}" style="width: 100%; margin-bottom: 15px;">
            </a>
        </div>
        <div class="col-sm-8">
            <a href="{{ sport.get_absolute_url }}">
                <h2><b>{{ sport.title }}</b></h2>
            </a>
            <p>{{ sport.body| truncatewords:50}}</p>
           <p>{{ sport.published_time }}</p>
        </div>
    </div>
</div>
{% endfor %}
{% endblock content %}

newsapp/templates/texnalogya_news.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Xorij habarlar {% endblock title %}
{% block content %}
{% for technology in texnalogyanews_list %}
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <a href="{{ technology.get_absolut_url }}">
                <img src="{{ technology.image.url }}" alt="{{technology.title }}" style="width: 100%; margin-bottom: 15px;">
            </a>
        </div>
        <div class="col-sm-8">
            <a href="{{ technology.get_absolute_url }}">
                <h2><b>{{ technology.title }}</b></h2>
            </a>
            <p>{{ technology.body| truncatewords:50}}</p>
           <p>{{ technology.published_time }}</p>
        </div>
    </div>
</div>
{% endfor %}
{% endblock content %}

newsapp/templates/xorij_news.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Xorij habarlar {% endblock title %}
{% block content %}
{% for xorij in xorijnews_list %}
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <a href="{{ xorij.get_absolut_url }}">
                <img src="{{ xorij.image.url }}" alt="{{ xorij.title }}" style="width: 100%; margin-bottom: 15px;">
            </a>
        </div>
        <div class="col-sm-8">
            <a href="{{ xorij.get_absolute_url}}">
                <h2><b>{{ xorij.title }}</b></h2>
            </a>
            <p>{{ xorij.body| truncatewords:50}}</p>
           <p>{{ xorij.published_time }}</p>
        </div>
    </div>
</div>
{% endfor %}
{% endblock content %}