accounts/urls.py
from django.urls import path
from .views import profile_page_view, signup_view, signUpView, UserRegisterCreateView, ProfileEditView, admin_page_view
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeView, PasswordChangeDoneView, PasswordResetView,
                                       PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView)
app_name ='accounts'

urlpatterns = [
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('password_change/',PasswordChangeView.as_view(),name='password_change'),
    path('password_change_done/',PasswordChangeDoneView.as_view(),name='password_change_done'),

    path('password-reset/',PasswordResetView.as_view(),name='password_reset'),
    path('password-reset/done',PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password-reset/<uidb64>/<token>',PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('password-reset/complete',PasswordResetCompleteView.as_view(),name='password_reset_complete'),

    # path('signup/',signup_view,name='signup')#fuktion view,
    path('signup/',signUpView.as_view(),name='signup'),#oddiy view
    # path('signup/',UserRegisterCreateView.as_view(),name='signup'),#generik view

    path('profile/',profile_page_view,name='profile'),
    path('profile/edit',ProfileEditView.as_view(),name='profile_edit'),


    path('adminpage/',admin_page_view,name='adminpage'),
]

config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),

]+i18n_patterns(
    path('i18n',include('django.conf.urls.i18n')),
    path('news/', include('newsapp.urls')),
    path('account/', include('accounts.urls'))
)

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newsapp/urls.py
from  django.urls import path
from .views import (ListPageView, DetailPageVieaw,
                    HomePageView, ContactPageView,
                    LocalNewsView, XorijNewsView,
                    SportNewsView, TechnologyNewsView,
                    UpdateNewsView, DeleteNewsView,
                    CreateNewsView, SearchListView, EditCommentView, DeleteCommentView, NewsLikeView)


app_name = 'newsapp'


urlpatterns = [
    path('search/',SearchListView.as_view(),name='search'),
    path('', HomePageView.as_view(),name='home_page'),
    path('create/',CreateNewsView.as_view(),name='create_news'),
    path('contact-us/',ContactPageView.as_view(),name='contact_page'),
    path('all-news/',ListPageView.as_view(),name='list_page'),
    path('local/',LocalNewsView.as_view(),name='local_news'),
    path('xorij/',XorijNewsView.as_view(),name='xorij_news'),
    path('sport/',SportNewsView.as_view(),name='sport_news'),
    path('technology/',TechnologyNewsView.as_view(),name='tech_news'),
    path('<slug:slug>/update/', UpdateNewsView.as_view(), name='update_news'),
    path('<slug:slug>/delete/', DeleteNewsView.as_view(), name='delete_news'),
    path('<slug:slug>/', DetailPageVieaw.as_view(), name='detail_page'),

    path('comment/<int:pk>/edit/',EditCommentView.as_view(),name='edit_comment'),
    path('comment/<int:pk>/delete/',DeleteCommentView.as_view(),name='delete_comment'),


    path("like/<slug:slug>/",NewsLikeView.as_view(),name='like'),
]

templates/base.html
{% load i18n %}
{% load static %}
{% load tz %}


<!DOCTYPE html>
<html>
<head>
<title>NewsFeed</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/font.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/li-scroller.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.fancybox.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/theme.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet"  href="{% static 'css/main.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
</head>
<body>
<div id="preloader">
  <div id="status">&nbsp;</div>
</div>
<a class="scrollToTop" href="#"><i class="fa fa-angle-up"></i></a>
<div class="container">
  <header id="header">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="header_top">
          <div class="header_top_left">
            <ul class="top_nav">
              <li><a href="{% url 'newsapp:home_page' %}">Home</a></li>
              <li><a href="#">About</a></li>
              <li><a href="{% url 'newsapp:contact_page' %} ">Contact</a></li>
              {% if request.user.is_superuser %}
              <li><a href="{% url 'accounts:adminpage'  %} ">Admin saxifasi</a></li>
              {% endif %}
              <li>
                <form>
                  <input action="{% url 'newsapp:search' %}" method="get" type="text" placeholder="Qidiruv..." name="q">
                  <button type="submit"><i class="fa fa-search"></i></button>
                </form>
              </li>
            </ul>
          </div>
          <div class="header_top_right">
            {% if request.user.is_authenticated %}
              <p> <a href="{% url 'accounts:profile' %}" style="color:yellow"> My Profile</a> </p>
            {% else %}
             <p> <a href="{% url 'accounts:login' %}" style="color:yellow"> Login </a></p>
            {% endif %}
            <p>Joriy vaqt: {% now "Y-m-d H:i" %}</p>
          </div>
        </div>
      </div>
      <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="header_bottom">
          <div class="logo_area"><a href="{% url 'newsapp:home_page' %}" class="logo"><img src="{% static 'images/logo.jpg' %}" alt=""></a></div>
          <div class="add_banner"><a href="#"><img src="{% static 'images/addbanner_728x90_V1.jpg' %}" alt=""></a></div>
        </div>
      </div>
    </div>
  </header>
  <section id="navArea">
    <nav class="navbar navbar-inverse" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav main_nav">
          <li class="active"><a href="{% url 'newsapp:home_page' %}"><span class="fa fa-home desktop-home"></span><span class="mobile-show">Home</span></a></li>
          <li><a href="{% url 'newsapp:local_news' %}">Maxalliy</a></li>
          <li><a href="{% url 'newsapp:xorij_news' %}">Xorij</a></li>
          <li><a href="{% url 'newsapp:sport_news' %}">Sport</a></li>
          <li><a href="{% url 'newsapp:tech_news' %}">Tehnolagiya</a></li>
          <li><a href="{% url 'newsapp:contact_page' %}">Contact Us</a></li>
          <li><a href="pages/404.html">404 Page</a></li>
        </ul>
      </div>
      <div>
        <ul>
          <li>
            <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
              <input name="next" type="hidden" value="{{ redirect_to }}">
              <select name="language">
                  {% get_current_language as LANGUAGE_CODE %}
                  {% get_available_languages as LANGUAGES %}
                  {% get_language_info_list for LANGUAGES as languages %}
                  {% for language in languages %}
                      <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                          {{ language.name_local }} ({{ language.code }})
                      </option>
                  {% endfor %}
              </select>
              <input type="submit" value="Go">
            </form>
          </li>
        </ul>
      </div>
    </nav>
  </section>
  <section id="newsSection">
    <div class="row">
      <div class="col-lg-12 col-md-12">
        <div class="latest_newsarea"> <span>So'ngi yangiliklar</span>
          <ul id="ticker01" class="news_sticker">
            {% if latest_news_list %}
              {% for news in latest_news_list %}
                <li><a href="#"><img src="{{ news.image.url }}" alt="{{ news.title }}">{{ news.title }}</a></li>
              {% endfor %}
            {% else %}
            <li>list topilmadi</li>
            {% endif %}
          </ul>
          <div class="social_area">
            <ul class="social_nav">
              <li class="facebook"><a href="#"></a></li>
              <li class="twitter"><a href="#"></a></li>
              <li class="flickr"><a href="#"></a></li>
              <li class="pinterest"><a href="#"></a></li>
              <li class="googleplus"><a href="#"></a></li>
              <li class="vimeo"><a href="#"></a></li>
              <li class="youtube"><a href="#"></a></li>
              <li class="mail"><a href="#"></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>


  {% block content %}

  {% endblock content %}
  <footer id="footer">
    <div class="footer_top">
      <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4">
          <div class="footer_widget wow fadeInLeftBig">
            <h2>Abdullayeva Mehrinoz</h2>
          </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4">
          <div class="footer_widget wow fadeInDown">
            <h2>Tags</h2>
            <ul class="tag_nav">

              {% if categories %}
                <ul>
                  {% for category in categories %}
                    <li><a href="#">{{category.name}}</a></li>
                  {% endfor %}
                </ul>
              {% endif %}
            </ul>
          </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4">
          <div class="footer_widget wow fadeInRightBig">
            <h2>Biz haqimizda </h2>
            <p>Andijon Davlat Universiteti IT injiniringi fakulteti Kompyuter ilmlari va dasturlash texnalogyalari talabasi Abdullayeva Mehrinoz </p>
            <address>
            address : Andijon viloyati
            Shahrixon tumani
            Tumor qishlog'i
            </address>
          </div>
        </div>
      </div>
    </div>
    <div class="footer_bottom">
      <p class="copyright"> &copy; 24/03/2025 <a href="index.html">NewsFeed</a></p>
      <p class="developer">Developed By Mehrinoz</p>
    </div>
  </footer>
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/slick.min.js' %}"></script>
<script src="{% static 'js/jquery.li-scroller.1.0.js' %}"></script>
<script src="{% static 'js/jquery.newsTicker.min.js' %}"></script>
<script src="{% static 'js/jquery.fancybox.pack.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/html5shiv.min.js' %}"></script>
<script src="{% static 'js/respond.min.js' %}"></script>
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %} contact page {% endblock title %}


{% block content %}
  <section id="contentSection">
    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-8">
        <div class="left_content">
          <div class="contact_area">
            <h2>Contact Us</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labolore magna aliqua. Ut enim ad minim veniam. Lorem ipsum dosectetur adipisicing elit, sed do.Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
            <form action="#" class="contact_form" method="post">{% csrf_token %}
              <input class="form-control" type="text" placeholder="Name*" name="name">
              <input class="form-control" type="email" placeholder="Email*" name="email">
              <textarea class="form-control" cols="30" rows="10" placeholder="Message*" name="text"></textarea>
              <input type="submit" value="Xabar yuborish">
            </form>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4">
        <aside class="right_content">
          <div class="single_sidebar">
            <h2><span>Popular Post</span></h2>
            <ul class="spost_nav">
              <li>
                <div class="media wow fadeInDown"> <a href="single_page.html" class="media-left"> <img alt="" src="../images/post_img1.jpg"> </a>
                  <div class="media-body"> <a href="single_page.html" class="catg_title"> Aliquam malesuada diam eget turpis varius 1</a> </div>
                </div>
              </li>
              <li>
                <div class="media wow fadeInDown"> <a href="single_page.html" class="media-left"> <img alt="" src="../images/post_img2.jpg"> </a>
                  <div class="media-body"> <a href="single_page.html" class="catg_title"> Aliquam malesuada diam eget turpis varius 2</a> </div>
                </div>
              </li>
              <li>
                <div class="media wow fadeInDown"> <a href="single_page.html" class="media-left"> <img alt="" src="../images/post_img1.jpg"> </a>
                  <div class="media-body"> <a href="single_page.html" class="catg_title"> Aliquam malesuada diam eget turpis varius 3</a> </div>
                </div>
              </li>
              <li>
                <div class="media wow fadeInDown"> <a href="single_page.html" class="media-left"> <img alt="" src="../images/post_img2.jpg"> </a>
                  <div class="media-body"> <a href="single_page.html" class="catg_title"> Aliquam malesuada diam eget turpis varius 4</a> </div>
                </div>
              </li>
            </ul>
          </div>
        </aside>
      </div>
    </div>
  </section>
{% endblock content %}

templates/searching_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Qidiruv sahifasi {% endblock title %}


{% block content %}
<h2>Qidiruv natijasi</h2>
{% endblock content %}